### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by jrmaddison**

### CODE REVIEW

**Comment by bearecinos** [comment]
Hi @jrmaddison just tested this with the latest conda env and it all works fine! so I am merging this ...

(cc. @dngoldberg )

**Review by bearecinos — APPROVED** [review]

**Comment by bearecinos** [comment]
oh I just realize does not let me merge this? do I have maintainer rights here?

**Comment by jrmaddison** [comment]
I think so -- as it's part of EdiGlacUQ

**Comment by bearecinos** [comment]
no it looks like I don't have that power ...

**Pull request merged**
